export const seedWeavers = [
	{ id: 'w-ramaswamy', name: 'Ramaswamy Chettiar', lineage_generation: '5th Generation Master Weaver', cluster: 'Kanchipuram, Tamil Nadu', portrait_url: 'https://images.unsplash.com/photo-1640292343595-889db1c8262e', bio: 'Custodian of the Chettiar family loom since 1998, celebrated for his revival of the vintage Swarna Kamal motif.' },
	{ id: 'w-anwar', name: 'Anwar Ali Ansari', lineage_generation: '4th Generation Karigar', cluster: 'Varanasi, Uttar Pradesh', portrait_url: 'https://images.unsplash.com/photo-1617694820985-a5476fe22722', bio: 'A Naksha-bandha master, Anwar draws every graph by hand — a lineage traced back to the Mughal ateliers.' },
	{ id: 'w-lakshmi', name: 'Lakshmi Devi', lineage_generation: '3rd Generation Weaver', cluster: 'Chanderi, Madhya Pradesh', portrait_url: 'https://images.unsplash.com/photo-1627705954911-940ac915d557', bio: 'One of the few women running her own pit-loom in Chanderi, known for her butis in beaten gold.' },
]

export const seedSarees = [
	{ slug: 'swarna-kamal-kanjivaram', title: 'Swarna Kamal Kanjivaram Mulberry Silk', loom_code: 'KNC-2026-08', origin_cluster: 'Kanchipuram, Tamil Nadu', weaver_id: 'w-ramaswamy', loom_architecture: 'Traditional Pit Loom with Double Shuttle Interlock (Petni)', weaving_duration_days: 42, artisan_hours: 320, warp_specification: '3-Ply Twisted Mulberry Silk (20/22 Denier)', weft_zari_composition: 'Pure Silver Gilt Zari — 98.5% Silver core with 24k Gold plating', story_narrative: 'A crimson tide that carries within it a garden of golden lotuses. The Swarna Kamal is woven on a temple-cluster loom where every dawn begins with the chanting of a hymn. The pallu — six feet of undulating gold — took forty-two days to unfurl.', retail_valuation_inr: 148000, available_units: 1, is_limited_heritage: true, status: 'published', is_silk_mark: true, is_handloom_mark: true, is_organic_dye: false, hero_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c', detail_urls: ['https://images.unsplash.com/photo-1613132923869-7da356bf6ec6', 'https://images.unsplash.com/photo-1630312874843-53f1295ae463', 'https://images.unsplash.com/photo-1640292343595-889db1c8262e'], materials: ['Pure Silk'], occasions: ['Muhurtham / Wedding'], tones: ['Crimson'] },
	{ slug: 'gulzar-banarasi-brocade', title: 'Gulzar Banarasi Kadhwa Brocade', loom_code: 'BNS-2026-14', origin_cluster: 'Varanasi, Uttar Pradesh', weaver_id: 'w-anwar', loom_architecture: 'Naksha-bandha Jaala Loom, hand-graphed', weaving_duration_days: 68, artisan_hours: 540, warp_specification: 'Katan Mulberry Silk (22/24 Denier), naturally reeled', weft_zari_composition: 'Antique Real Zari with lac-dyed silk meenakari', story_narrative: 'A courtyard in bloom at dusk. Every buti in the Gulzar is a Kadhwa — a small tapestry within the sari, each flower cut and re-tied so that no thread crosses another. Sixty-eight sunrises passed before Anwar cut it from the loom.', retail_valuation_inr: 212000, available_units: 1, is_limited_heritage: true, status: 'published', is_silk_mark: true, is_handloom_mark: true, is_organic_dye: true, hero_url: 'https://images.unsplash.com/photo-1610189338175-0782dfdb0c04', detail_urls: ['https://images.unsplash.com/photo-1616057767359-ae31521e2317', 'https://images.unsplash.com/photo-1617694820985-a5476fe22722'], materials: ['Pure Silk'], occasions: ['Festive Royal', 'Diplomatic Gifting'], tones: ['Saffron'] },
	{ slug: 'nilambari-chanderi-tissue', title: 'Nilambari Chanderi Tissue Handloom', loom_code: 'CHN-2026-04', origin_cluster: 'Chanderi, Madhya Pradesh', weaver_id: 'w-lakshmi', loom_architecture: 'Traditional Pit Loom, single shuttle', weaving_duration_days: 21, artisan_hours: 160, warp_specification: 'Hand-reeled Katan Silk (16 Denier)', weft_zari_composition: 'Fine Silver Zari with Chanderi cotton weft — signature tissue feel', story_narrative: 'The colour of a monsoon evening in Bundelkhand. Nilambari drifts like mist across the body — three weeks of dawn-to-dusk weaving compressed into a whisper of tissue.', retail_valuation_inr: 68000, available_units: 3, is_limited_heritage: false, status: 'published', is_silk_mark: true, is_handloom_mark: true, is_organic_dye: true, hero_url: 'https://images.unsplash.com/photo-1610030469245-ab65c4583802', detail_urls: ['https://images.unsplash.com/photo-1627705954911-940ac915d557'], materials: ['Pure Silk', 'Handspun Cotton'], occasions: ['Casual Heritage', 'Festive Royal'], tones: ['Indigo', 'Emerald'] },
	{ slug: 'agnideepa-madder-korvai', title: 'Agnideepa Madder-Dyed Korvai Silk', loom_code: 'KNC-2026-11', origin_cluster: 'Kanchipuram, Tamil Nadu', weaver_id: 'w-ramaswamy', loom_architecture: 'Korvai Three-Shuttle Interlock Pit Loom', weaving_duration_days: 55, artisan_hours: 410, warp_specification: '2-Ply Mulberry Silk, madder-root dyed', weft_zari_composition: 'Contrast Korvai border in gilt zari — hand-linked at every pick', story_narrative: 'Dyed in the roots of the madder plant harvested from the Cauvery basin, Agnideepa carries the pigment of temple lamps at dusk. Its border is bound not stitched — a mark of the true Korvai lineage.', retail_valuation_inr: 176000, available_units: 1, is_limited_heritage: true, status: 'published', is_silk_mark: true, is_handloom_mark: true, is_organic_dye: true, hero_url: 'https://images.unsplash.com/photo-1610030468706-9a6dbad49b0a', detail_urls: ['https://images.unsplash.com/photo-1613132923869-7da356bf6ec6', 'https://images.unsplash.com/photo-1630312874843-53f1295ae463'], materials: ['Pure Silk'], occasions: ['Muhurtham / Wedding', 'Festive Royal'], tones: ['Crimson', 'Saffron'] },
]